sudo: required
language: bash
env:
  - alpine_version=3.12.0
before_install:
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
script:
# activate experimental docker feature
  - export DOCKER_CLI_EXPERIMENTAL=enabled
# prepare qemu
  - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
# get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v5.1.0-2/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
# create new builder
  - docker buildx create --name builder
  - docker buildx use builder
  - docker buildx inspect --bootstrap
# if master branch, build image and push it
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker buildx build --platform linux/amd64,linux/arm/v7 --build-arg alpine_version=$alpine_version -t  dtroncy/rpi-alpine:latest --push .
      docker buildx build --platform linux/amd64,linux/arm/v7 --build-arg alpine_version=$alpine_version -t  dtroncy/rpi-alpine:$alpine_version --push .
    fi
# if develop branch, build image and load it
  - >
    if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker buildx build --platform linux/amd64,linux/arm/v7 --build-arg alpine_version=$alpine_version -t  dtroncy/rpi-alpine:latest .
      docker buildx build --platform linux/amd64,linux/arm/v7 --build-arg alpine_version=$alpine_version -t  dtroncy/rpi-alpine:$alpine_version .
    fi