sudo: required
services:
  - docker
language: bash
env:
  - alpine_version=3.9
addons:
  apt:
    packages:
      - docker-ce
script:
# activate experimental docker feature
  - export DOCKER_CLI_EXPERIMENTAL=enabled
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v4.1.0-1/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
# build image
  - docker build --build-arg alpine_version=$alpine_version -t dtroncy/rpi-alpine .
# test image
  - docker run dtroncy/rpi-alpine uname -a
# push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker tag dtroncy/rpi-alpine dtroncy/rpi-alpine:$alpine_version
      docker push dtroncy/rpi-alpine:$alpine_version
      docker push dtroncy/rpi-alpine
    fi
# Create and update image manifest
  - docker manifest create dtroncy/rpi-alpine:latest dtroncy/rpi-alpine:latest
  - docker manifest annotate dtroncy/rpi-alpine:latest dtroncy/rpi-alpine:latest --arch arm
  - docker manifest push dtroncy/rpi-alpine:latest
  - docker manifest create dtroncy/rpi-alpine:$alpine_version dtroncy/rpi-alpine:$alpine_version
  - docker manifest annotate dtroncy/rpi-alpine:$alpine_version dtroncy/rpi-alpine:$alpine_version --arch arm
  - docker manifest push dtroncy/rpi-alpine:$alpine_version