sudo: required
services:
  - docker
language: bash
env:
  - alpine_version=3.8
script:
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
# build image
  - docker build --build-arg alpine_version=$alpine_version -t dtroncy/rpi-alpine .
# test image
  - docker run dtroncy/rpi-alpine uname -a
# push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker tag dtroncy/rpi-alpine dtroncy/rpi-alpine:$alpine_version
      docker push dtroncy/rpi-alpine:$alpine_version
      docker push dtroncy/rpi-alpine
    fi